/** Slack/GitHub-style emoji shortcodes for the custom-glyph text editor.
 *
 * Browsers don't expand `:joy:` the way chat apps do — users type a
 * shortcode into the plain input and nothing converts, so the Shape
 * panel does it here. `expandEmojiShortcodes` swaps complete `:name:`
 * tokens as they're typed; `expandEmojiInput` additionally accepts a
 * bare `:name` (no closing colon) when it's the whole input, for
 * submit-time forgiveness.
 *
 * The map is a curated common set, not the full CLDR list — unknown
 * names pass through unchanged (the user sees their literal text and
 * the length cap explains itself). The system emoji picker covers the
 * long tail. */
export const EMOJI_SHORTCODES: Record<string, string> = {
	// Smileys
	grinning: "😀",
	smiley: "😃",
	smile: "😄",
	grin: "😁",
	laughing: "😆",
	joy: "😂",
	rofl: "🤣",
	slightly_smiling_face: "🙂",
	upside_down_face: "🙃",
	wink: "😉",
	blush: "😊",
	innocent: "😇",
	heart_eyes: "😍",
	star_struck: "🤩",
	kissing_heart: "😘",
	yum: "😋",
	stuck_out_tongue: "😛",
	stuck_out_tongue_winking_eye: "😜",
	zany_face: "🤪",
	thinking: "🤔",
	neutral_face: "😐",
	expressionless: "😑",
	smirk: "😏",
	unamused: "😒",
	roll_eyes: "🙄",
	grimacing: "😬",
	relieved: "😌",
	pensive: "😔",
	sleeping: "😴",
	mask: "😷",
	sunglasses: "😎",
	nerd_face: "🤓",
	confused: "😕",
	worried: "😟",
	open_mouth: "😮",
	astonished: "😲",
	flushed: "😳",
	scream: "😱",
	fearful: "😨",
	disappointed: "😞",
	sob: "😭",
	cry: "😢",
	angry: "😠",
	rage: "😡",
	exploding_head: "🤯",
	sweat_smile: "😅",
	skull: "💀",
	ghost: "👻",
	alien: "👽",
	robot: "🤖",
	clown_face: "🤡",
	poop: "💩",
	hankey: "💩",
	// Hearts
	heart: "❤️",
	orange_heart: "🧡",
	yellow_heart: "💛",
	green_heart: "💚",
	blue_heart: "💙",
	purple_heart: "💜",
	black_heart: "🖤",
	white_heart: "🤍",
	brown_heart: "🤎",
	broken_heart: "💔",
	two_hearts: "💕",
	sparkling_heart: "💖",
	heartpulse: "💗",
	cupid: "💘",
	gift_heart: "💝",
	// Gestures & body
	thumbsup: "👍",
	"+1": "👍",
	thumbsdown: "👎",
	"-1": "👎",
	ok_hand: "👌",
	clap: "👏",
	wave: "👋",
	raised_hands: "🙌",
	pray: "🙏",
	muscle: "💪",
	handshake: "🤝",
	crossed_fingers: "🤞",
	point_right: "👉",
	point_left: "👈",
	point_up_2: "👆",
	point_down: "👇",
	fist: "✊",
	eyes: "👀",
	brain: "🧠",
	ear: "👂",
	nose: "👃",
	lips: "👄",
	tongue: "👅",
	speech_balloon: "💬",
	thought_balloon: "💭",
	zzz: "💤",
	dash: "💨",
	sweat_drops: "💦",
	// Symbols & effects
	fire: "🔥",
	star: "⭐",
	star2: "🌟",
	sparkles: "✨",
	zap: "⚡",
	boom: "💥",
	collision: "💥",
	x: "❌",
	white_check_mark: "✅",
	heavy_check_mark: "✔️",
	warning: "⚠️",
	question: "❓",
	exclamation: "❗",
	"100": "💯",
	tada: "🎉",
	confetti_ball: "🎊",
	balloon: "🎈",
	gift: "🎁",
	trophy: "🏆",
	"1st_place_medal": "🥇",
	crown: "👑",
	gem: "💎",
	bell: "🔔",
	bulb: "💡",
	gear: "⚙️",
	hammer: "🔨",
	wrench: "🔧",
	hammer_and_wrench: "🛠️",
	lock: "🔒",
	unlock: "🔓",
	key: "🔑",
	mag: "🔍",
	pushpin: "📌",
	paperclip: "📎",
	link: "🔗",
	scissors: "✂️",
	pencil2: "✏️",
	memo: "📝",
	book: "📖",
	books: "📚",
	bookmark: "🔖",
	calendar: "📅",
	alarm_clock: "⏰",
	hourglass: "⌛",
	watch: "⌚",
	moneybag: "💰",
	dollar: "💵",
	credit_card: "💳",
	chart_with_upwards_trend: "📈",
	chart_with_downwards_trend: "📉",
	bar_chart: "📊",
	clipboard: "📋",
	briefcase: "💼",
	package: "📦",
	envelope: "✉️",
	email: "✉️",
	iphone: "📱",
	computer: "💻",
	camera: "📷",
	clapper: "🎬",
	tv: "📺",
	microphone: "🎤",
	headphones: "🎧",
	musical_note: "🎵",
	notes: "🎶",
	guitar: "🎸",
	violin: "🎻",
	trumpet: "🎺",
	drum: "🥁",
	art: "🎨",
	video_game: "🎮",
	game_die: "🎲",
	dart: "🎯",
	bowling: "🎳",
	checkered_flag: "🏁",
	triangular_flag_on_post: "🚩",
	// Sports
	soccer: "⚽",
	basketball: "🏀",
	football: "🏈",
	baseball: "⚾",
	tennis: "🎾",
	volleyball: "🏐",
	golf: "⛳",
	ski: "🎿",
	medal_sports: "🏅",
	bike: "🚲",
	// Transport & places
	car: "🚗",
	red_car: "🚗",
	taxi: "🚕",
	bus: "🚌",
	truck: "🚚",
	fire_engine: "🚒",
	police_car: "🚓",
	ambulance: "🚑",
	tractor: "🚜",
	airplane: "✈️",
	rocket: "🚀",
	helicopter: "🚁",
	sailboat: "⛵",
	boat: "⛵",
	ship: "🚢",
	anchor: "⚓",
	construction: "🚧",
	fuelpump: "⛽",
	house: "🏠",
	office: "🏢",
	school: "🏫",
	hospital: "🏥",
	bank: "🏦",
	hotel: "🏨",
	church: "⛪",
	castle: "🏰",
	tent: "⛺",
	volcano: "🌋",
	earth_americas: "🌎",
	earth_africa: "🌍",
	earth_asia: "🌏",
	globe_with_meridians: "🌐",
	compass: "🧭",
	// Weather & nature
	sunny: "☀️",
	sun_with_face: "🌞",
	crescent_moon: "🌙",
	full_moon: "🌕",
	new_moon: "🌑",
	cloud: "☁️",
	partly_sunny: "⛅",
	umbrella: "☔",
	snowflake: "❄️",
	snowman: "⛄",
	rainbow: "🌈",
	ocean: "🌊",
	droplet: "💧",
	seedling: "🌱",
	herb: "🌿",
	four_leaf_clover: "🍀",
	leaves: "🍃",
	fallen_leaf: "🍂",
	maple_leaf: "🍁",
	evergreen_tree: "🌲",
	deciduous_tree: "🌳",
	palm_tree: "🌴",
	cactus: "🌵",
	rose: "🌹",
	tulip: "🌷",
	sunflower: "🌻",
	hibiscus: "🌺",
	cherry_blossom: "🌸",
	bouquet: "💐",
	mushroom: "🍄",
	// Animals
	dog: "🐶",
	cat: "🐱",
	mouse: "🐭",
	hamster: "🐹",
	rabbit: "🐰",
	fox_face: "🦊",
	bear: "🐻",
	panda_face: "🐼",
	koala: "🐨",
	tiger: "🐯",
	lion: "🦁",
	cow: "🐮",
	pig: "🐷",
	frog: "🐸",
	monkey_face: "🐵",
	monkey: "🐒",
	chicken: "🐔",
	penguin: "🐧",
	bird: "🐦",
	baby_chick: "🐤",
	hatching_chick: "🐣",
	duck: "🦆",
	owl: "🦉",
	bat: "🦇",
	wolf: "🐺",
	boar: "🐗",
	horse: "🐴",
	unicorn: "🦄",
	bee: "🐝",
	bug: "🐛",
	butterfly: "🦋",
	snail: "🐌",
	lady_beetle: "🐞",
	ant: "🐜",
	turtle: "🐢",
	snake: "🐍",
	lizard: "🦎",
	octopus: "🐙",
	squid: "🦑",
	shrimp: "🦐",
	lobster: "🦞",
	crab: "🦀",
	blowfish: "🐡",
	tropical_fish: "🐠",
	fish: "🐟",
	shark: "🦈",
	dolphin: "🐬",
	whale: "🐳",
	elephant: "🐘",
	giraffe: "🦒",
	camel: "🐫",
	zebra: "🦓",
	gorilla: "🦍",
	sheep: "🐑",
	goat: "🐐",
	deer: "🦌",
	dragon: "🐉",
	// Food & drink
	apple: "🍎",
	green_apple: "🍏",
	banana: "🍌",
	tangerine: "🍊",
	lemon: "🍋",
	watermelon: "🍉",
	grapes: "🍇",
	strawberry: "🍓",
	melon: "🍈",
	cherries: "🍒",
	peach: "🍑",
	mango: "🥭",
	pineapple: "🍍",
	coconut: "🥥",
	kiwi_fruit: "🥝",
	avocado: "🥑",
	eggplant: "🍆",
	potato: "🥔",
	carrot: "🥕",
	corn: "🌽",
	hot_pepper: "🌶️",
	cucumber: "🥒",
	broccoli: "🥦",
	tomato: "🍅",
	bread: "🍞",
	croissant: "🥐",
	pretzel: "🥨",
	cheese: "🧀",
	egg: "🥚",
	fried_egg: "🍳",
	bacon: "🥓",
	pancakes: "🥞",
	hamburger: "🍔",
	fries: "🍟",
	pizza: "🍕",
	hotdog: "🌭",
	taco: "🌮",
	burrito: "🌯",
	sandwich: "🥪",
	ramen: "🍜",
	spaghetti: "🍝",
	sushi: "🍣",
	bento: "🍱",
	curry: "🍛",
	rice: "🍚",
	dumpling: "🥟",
	cake: "🍰",
	birthday: "🎂",
	cupcake: "🧁",
	cookie: "🍪",
	doughnut: "🍩",
	donut: "🍩",
	candy: "🍬",
	lollipop: "🍭",
	chocolate_bar: "🍫",
	popcorn: "🍿",
	honey_pot: "🍯",
	ice_cream: "🍨",
	icecream: "🍦",
	coffee: "☕",
	tea: "🍵",
	beer: "🍺",
	beers: "🍻",
	wine_glass: "🍷",
	cocktail: "🍸",
	tropical_drink: "🍹",
	champagne: "🍾",
	milk_glass: "🥛",
	// Arrows
	arrow_up: "⬆️",
	arrow_down: "⬇️",
	arrow_left: "⬅️",
	arrow_right: "➡️",
}

const SHORTCODE_TOKEN = /:([\w+-]+):/g

/** Replace every complete `:name:` token whose name is in the map;
 * unknown names stay literal. Case-insensitive. Runs on every keystroke
 * in the custom-glyph editor, so typing the closing colon converts the
 * shortcode in place. */
export const expandEmojiShortcodes = (text: string): string =>
	text.replace(
		SHORTCODE_TOKEN,
		(token, name: string) => EMOJI_SHORTCODES[name.toLowerCase()] ?? token
	)

/** Submit-time expansion: complete `:name:` tokens everywhere, plus a
 * bare `:name` (closing colon never typed) when it's the entire input —
 * users reasonably stop typing once they've named the emoji. */
export const expandEmojiInput = (text: string): string => {
	const expanded = expandEmojiShortcodes(text.trim())
	const name = /^:([\w+-]+):?$/.exec(expanded)?.[1]
	if (name) {
		const hit = EMOJI_SHORTCODES[name.toLowerCase()]
		if (hit) return hit
	}
	return expanded
}
