/**
 * Static lookup of ISO 3166-1 countries (plus the few non-ISO / disputed
 * entries the world-atlas geometry ships).
 *
 * world-atlas `countries-110m.json` country features carry `id` = numeric
 * ISO 3166-1 code (as a string) and `properties.name` = an English name, but
 * NOT the alpha-2 / alpha-3 codes. This table maps numeric -> {iso2, iso3,
 * name} so `resolveGeography` can recognize "840" / "US" / "USA" / a country
 * name and join them all to the geometry's numeric id.
 *
 * - `numeric`: 3-digit zero-padded ISO 3166-1 numeric code (string; leading
 *   zeros matter, e.g. Afghanistan "004").
 * - `iso2`: uppercase alpha-2, or "" if none exists (disputed territories).
 * - `iso3`: uppercase alpha-3, or "" if none exists.
 * - `name`: English country name. Where the country appears in the world-atlas
 *   geometry, this is the geometry's `properties.name` verbatim so name-joins
 *   match the rendered features; otherwise the common ISO English short name.
 *
 * Disputed / non-ISO entries present in the world-atlas geometry but lacking a
 * standard numeric id (`id === undefined`) are given a synthetic numeric so
 * the table stays keyable; they join to the geometry by NAME, not numeric:
 *   - Kosovo: numeric "383" (de-facto user-assigned XK/XKX).
 *   - N. Cyprus: numeric "900", no ISO codes ("").
 *   - Somaliland: numeric "901", no ISO codes ("").
 */
export type IsoCountryRow = {
	numeric: string
	iso2: string
	iso3: string
	name: string
}

export const ISO_COUNTRIES: readonly IsoCountryRow[] = [
	{ numeric: "004", iso2: "AF", iso3: "AFG", name: "Afghanistan" },
	{ numeric: "008", iso2: "AL", iso3: "ALB", name: "Albania" },
	{ numeric: "010", iso2: "AQ", iso3: "ATA", name: "Antarctica" },
	{ numeric: "012", iso2: "DZ", iso3: "DZA", name: "Algeria" },
	{ numeric: "016", iso2: "AS", iso3: "ASM", name: "American Samoa" },
	{ numeric: "020", iso2: "AD", iso3: "AND", name: "Andorra" },
	{ numeric: "024", iso2: "AO", iso3: "AGO", name: "Angola" },
	{ numeric: "028", iso2: "AG", iso3: "ATG", name: "Antigua and Barbuda" },
	{ numeric: "031", iso2: "AZ", iso3: "AZE", name: "Azerbaijan" },
	{ numeric: "032", iso2: "AR", iso3: "ARG", name: "Argentina" },
	{ numeric: "036", iso2: "AU", iso3: "AUS", name: "Australia" },
	{ numeric: "040", iso2: "AT", iso3: "AUT", name: "Austria" },
	{ numeric: "044", iso2: "BS", iso3: "BHS", name: "Bahamas" },
	{ numeric: "048", iso2: "BH", iso3: "BHR", name: "Bahrain" },
	{ numeric: "050", iso2: "BD", iso3: "BGD", name: "Bangladesh" },
	{ numeric: "051", iso2: "AM", iso3: "ARM", name: "Armenia" },
	{ numeric: "052", iso2: "BB", iso3: "BRB", name: "Barbados" },
	{ numeric: "056", iso2: "BE", iso3: "BEL", name: "Belgium" },
	{ numeric: "060", iso2: "BM", iso3: "BMU", name: "Bermuda" },
	{ numeric: "064", iso2: "BT", iso3: "BTN", name: "Bhutan" },
	{ numeric: "068", iso2: "BO", iso3: "BOL", name: "Bolivia" },
	{
		numeric: "070",
		iso2: "BA",
		iso3: "BIH",
		name: "Bosnia and Herz.",
	},
	{ numeric: "072", iso2: "BW", iso3: "BWA", name: "Botswana" },
	{ numeric: "074", iso2: "BV", iso3: "BVT", name: "Bouvet Island" },
	{ numeric: "076", iso2: "BR", iso3: "BRA", name: "Brazil" },
	{ numeric: "084", iso2: "BZ", iso3: "BLZ", name: "Belize" },
	{
		numeric: "086",
		iso2: "IO",
		iso3: "IOT",
		name: "British Indian Ocean Territory",
	},
	{ numeric: "090", iso2: "SB", iso3: "SLB", name: "Solomon Is." },
	{ numeric: "092", iso2: "VG", iso3: "VGB", name: "British Virgin Islands" },
	{ numeric: "096", iso2: "BN", iso3: "BRN", name: "Brunei" },
	{ numeric: "100", iso2: "BG", iso3: "BGR", name: "Bulgaria" },
	{ numeric: "104", iso2: "MM", iso3: "MMR", name: "Myanmar" },
	{ numeric: "108", iso2: "BI", iso3: "BDI", name: "Burundi" },
	{ numeric: "112", iso2: "BY", iso3: "BLR", name: "Belarus" },
	{ numeric: "116", iso2: "KH", iso3: "KHM", name: "Cambodia" },
	{ numeric: "120", iso2: "CM", iso3: "CMR", name: "Cameroon" },
	{ numeric: "124", iso2: "CA", iso3: "CAN", name: "Canada" },
	{ numeric: "132", iso2: "CV", iso3: "CPV", name: "Cabo Verde" },
	{ numeric: "136", iso2: "KY", iso3: "CYM", name: "Cayman Islands" },
	{
		numeric: "140",
		iso2: "CF",
		iso3: "CAF",
		name: "Central African Rep.",
	},
	{ numeric: "144", iso2: "LK", iso3: "LKA", name: "Sri Lanka" },
	{ numeric: "148", iso2: "TD", iso3: "TCD", name: "Chad" },
	{ numeric: "152", iso2: "CL", iso3: "CHL", name: "Chile" },
	{ numeric: "156", iso2: "CN", iso3: "CHN", name: "China" },
	{ numeric: "158", iso2: "TW", iso3: "TWN", name: "Taiwan" },
	{ numeric: "162", iso2: "CX", iso3: "CXR", name: "Christmas Island" },
	{ numeric: "166", iso2: "CC", iso3: "CCK", name: "Cocos (Keeling) Islands" },
	{ numeric: "170", iso2: "CO", iso3: "COL", name: "Colombia" },
	{ numeric: "174", iso2: "KM", iso3: "COM", name: "Comoros" },
	{ numeric: "175", iso2: "YT", iso3: "MYT", name: "Mayotte" },
	{ numeric: "178", iso2: "CG", iso3: "COG", name: "Congo" },
	{ numeric: "180", iso2: "CD", iso3: "COD", name: "Dem. Rep. Congo" },
	{ numeric: "184", iso2: "CK", iso3: "COK", name: "Cook Islands" },
	{ numeric: "188", iso2: "CR", iso3: "CRI", name: "Costa Rica" },
	{ numeric: "191", iso2: "HR", iso3: "HRV", name: "Croatia" },
	{ numeric: "192", iso2: "CU", iso3: "CUB", name: "Cuba" },
	{ numeric: "196", iso2: "CY", iso3: "CYP", name: "Cyprus" },
	{ numeric: "203", iso2: "CZ", iso3: "CZE", name: "Czechia" },
	{ numeric: "204", iso2: "BJ", iso3: "BEN", name: "Benin" },
	{ numeric: "208", iso2: "DK", iso3: "DNK", name: "Denmark" },
	{ numeric: "212", iso2: "DM", iso3: "DMA", name: "Dominica" },
	{ numeric: "214", iso2: "DO", iso3: "DOM", name: "Dominican Rep." },
	{ numeric: "218", iso2: "EC", iso3: "ECU", name: "Ecuador" },
	{ numeric: "222", iso2: "SV", iso3: "SLV", name: "El Salvador" },
	{ numeric: "226", iso2: "GQ", iso3: "GNQ", name: "Eq. Guinea" },
	{ numeric: "231", iso2: "ET", iso3: "ETH", name: "Ethiopia" },
	{ numeric: "232", iso2: "ER", iso3: "ERI", name: "Eritrea" },
	{ numeric: "233", iso2: "EE", iso3: "EST", name: "Estonia" },
	{ numeric: "234", iso2: "FO", iso3: "FRO", name: "Faroe Islands" },
	{ numeric: "238", iso2: "FK", iso3: "FLK", name: "Falkland Is." },
	{
		numeric: "239",
		iso2: "GS",
		iso3: "SGS",
		name: "South Georgia and the South Sandwich Islands",
	},
	{ numeric: "242", iso2: "FJ", iso3: "FJI", name: "Fiji" },
	{ numeric: "246", iso2: "FI", iso3: "FIN", name: "Finland" },
	{ numeric: "248", iso2: "AX", iso3: "ALA", name: "Åland Islands" },
	{ numeric: "250", iso2: "FR", iso3: "FRA", name: "France" },
	{ numeric: "254", iso2: "GF", iso3: "GUF", name: "French Guiana" },
	{ numeric: "258", iso2: "PF", iso3: "PYF", name: "French Polynesia" },
	{
		numeric: "260",
		iso2: "TF",
		iso3: "ATF",
		name: "Fr. S. Antarctic Lands",
	},
	{ numeric: "262", iso2: "DJ", iso3: "DJI", name: "Djibouti" },
	{ numeric: "266", iso2: "GA", iso3: "GAB", name: "Gabon" },
	{ numeric: "268", iso2: "GE", iso3: "GEO", name: "Georgia" },
	{ numeric: "270", iso2: "GM", iso3: "GMB", name: "Gambia" },
	{ numeric: "275", iso2: "PS", iso3: "PSE", name: "Palestine" },
	{ numeric: "276", iso2: "DE", iso3: "DEU", name: "Germany" },
	{ numeric: "288", iso2: "GH", iso3: "GHA", name: "Ghana" },
	{ numeric: "292", iso2: "GI", iso3: "GIB", name: "Gibraltar" },
	{ numeric: "296", iso2: "KI", iso3: "KIR", name: "Kiribati" },
	{ numeric: "300", iso2: "GR", iso3: "GRC", name: "Greece" },
	{ numeric: "304", iso2: "GL", iso3: "GRL", name: "Greenland" },
	{ numeric: "308", iso2: "GD", iso3: "GRD", name: "Grenada" },
	{ numeric: "312", iso2: "GP", iso3: "GLP", name: "Guadeloupe" },
	{ numeric: "316", iso2: "GU", iso3: "GUM", name: "Guam" },
	{ numeric: "320", iso2: "GT", iso3: "GTM", name: "Guatemala" },
	{ numeric: "324", iso2: "GN", iso3: "GIN", name: "Guinea" },
	{ numeric: "328", iso2: "GY", iso3: "GUY", name: "Guyana" },
	{ numeric: "332", iso2: "HT", iso3: "HTI", name: "Haiti" },
	{
		numeric: "334",
		iso2: "HM",
		iso3: "HMD",
		name: "Heard Island and McDonald Islands",
	},
	{ numeric: "336", iso2: "VA", iso3: "VAT", name: "Holy See" },
	{ numeric: "340", iso2: "HN", iso3: "HND", name: "Honduras" },
	{ numeric: "344", iso2: "HK", iso3: "HKG", name: "Hong Kong" },
	{ numeric: "348", iso2: "HU", iso3: "HUN", name: "Hungary" },
	{ numeric: "352", iso2: "IS", iso3: "ISL", name: "Iceland" },
	{ numeric: "356", iso2: "IN", iso3: "IND", name: "India" },
	{ numeric: "360", iso2: "ID", iso3: "IDN", name: "Indonesia" },
	{ numeric: "364", iso2: "IR", iso3: "IRN", name: "Iran" },
	{ numeric: "368", iso2: "IQ", iso3: "IRQ", name: "Iraq" },
	{ numeric: "372", iso2: "IE", iso3: "IRL", name: "Ireland" },
	{ numeric: "376", iso2: "IL", iso3: "ISR", name: "Israel" },
	{ numeric: "380", iso2: "IT", iso3: "ITA", name: "Italy" },
	{ numeric: "384", iso2: "CI", iso3: "CIV", name: "Côte d'Ivoire" },
	{ numeric: "388", iso2: "JM", iso3: "JAM", name: "Jamaica" },
	{ numeric: "392", iso2: "JP", iso3: "JPN", name: "Japan" },
	{ numeric: "398", iso2: "KZ", iso3: "KAZ", name: "Kazakhstan" },
	{ numeric: "400", iso2: "JO", iso3: "JOR", name: "Jordan" },
	{ numeric: "404", iso2: "KE", iso3: "KEN", name: "Kenya" },
	{ numeric: "408", iso2: "KP", iso3: "PRK", name: "North Korea" },
	{ numeric: "410", iso2: "KR", iso3: "KOR", name: "South Korea" },
	{ numeric: "414", iso2: "KW", iso3: "KWT", name: "Kuwait" },
	{ numeric: "417", iso2: "KG", iso3: "KGZ", name: "Kyrgyzstan" },
	{ numeric: "418", iso2: "LA", iso3: "LAO", name: "Laos" },
	{ numeric: "422", iso2: "LB", iso3: "LBN", name: "Lebanon" },
	{ numeric: "426", iso2: "LS", iso3: "LSO", name: "Lesotho" },
	{ numeric: "428", iso2: "LV", iso3: "LVA", name: "Latvia" },
	{ numeric: "430", iso2: "LR", iso3: "LBR", name: "Liberia" },
	{ numeric: "434", iso2: "LY", iso3: "LBY", name: "Libya" },
	{ numeric: "438", iso2: "LI", iso3: "LIE", name: "Liechtenstein" },
	{ numeric: "440", iso2: "LT", iso3: "LTU", name: "Lithuania" },
	{ numeric: "442", iso2: "LU", iso3: "LUX", name: "Luxembourg" },
	{ numeric: "446", iso2: "MO", iso3: "MAC", name: "Macao" },
	{ numeric: "450", iso2: "MG", iso3: "MDG", name: "Madagascar" },
	{ numeric: "454", iso2: "MW", iso3: "MWI", name: "Malawi" },
	{ numeric: "458", iso2: "MY", iso3: "MYS", name: "Malaysia" },
	{ numeric: "462", iso2: "MV", iso3: "MDV", name: "Maldives" },
	{ numeric: "466", iso2: "ML", iso3: "MLI", name: "Mali" },
	{ numeric: "470", iso2: "MT", iso3: "MLT", name: "Malta" },
	{ numeric: "474", iso2: "MQ", iso3: "MTQ", name: "Martinique" },
	{ numeric: "478", iso2: "MR", iso3: "MRT", name: "Mauritania" },
	{ numeric: "480", iso2: "MU", iso3: "MUS", name: "Mauritius" },
	{ numeric: "484", iso2: "MX", iso3: "MEX", name: "Mexico" },
	{ numeric: "492", iso2: "MC", iso3: "MCO", name: "Monaco" },
	{ numeric: "496", iso2: "MN", iso3: "MNG", name: "Mongolia" },
	{ numeric: "498", iso2: "MD", iso3: "MDA", name: "Moldova" },
	{ numeric: "499", iso2: "ME", iso3: "MNE", name: "Montenegro" },
	{ numeric: "500", iso2: "MS", iso3: "MSR", name: "Montserrat" },
	{ numeric: "504", iso2: "MA", iso3: "MAR", name: "Morocco" },
	{ numeric: "508", iso2: "MZ", iso3: "MOZ", name: "Mozambique" },
	{ numeric: "512", iso2: "OM", iso3: "OMN", name: "Oman" },
	{ numeric: "516", iso2: "NA", iso3: "NAM", name: "Namibia" },
	{ numeric: "520", iso2: "NR", iso3: "NRU", name: "Nauru" },
	{ numeric: "524", iso2: "NP", iso3: "NPL", name: "Nepal" },
	{ numeric: "528", iso2: "NL", iso3: "NLD", name: "Netherlands" },
	{ numeric: "531", iso2: "CW", iso3: "CUW", name: "Curaçao" },
	{ numeric: "533", iso2: "AW", iso3: "ABW", name: "Aruba" },
	{ numeric: "534", iso2: "SX", iso3: "SXM", name: "Sint Maarten" },
	{ numeric: "535", iso2: "BQ", iso3: "BES", name: "Bonaire" },
	{ numeric: "540", iso2: "NC", iso3: "NCL", name: "New Caledonia" },
	{ numeric: "548", iso2: "VU", iso3: "VUT", name: "Vanuatu" },
	{ numeric: "554", iso2: "NZ", iso3: "NZL", name: "New Zealand" },
	{ numeric: "558", iso2: "NI", iso3: "NIC", name: "Nicaragua" },
	{ numeric: "562", iso2: "NE", iso3: "NER", name: "Niger" },
	{ numeric: "566", iso2: "NG", iso3: "NGA", name: "Nigeria" },
	{ numeric: "570", iso2: "NU", iso3: "NIU", name: "Niue" },
	{ numeric: "574", iso2: "NF", iso3: "NFK", name: "Norfolk Island" },
	{
		numeric: "580",
		iso2: "MP",
		iso3: "MNP",
		name: "Northern Mariana Islands",
	},
	{ numeric: "578", iso2: "NO", iso3: "NOR", name: "Norway" },
	{ numeric: "583", iso2: "FM", iso3: "FSM", name: "Micronesia" },
	{ numeric: "584", iso2: "MH", iso3: "MHL", name: "Marshall Islands" },
	{ numeric: "585", iso2: "PW", iso3: "PLW", name: "Palau" },
	{ numeric: "586", iso2: "PK", iso3: "PAK", name: "Pakistan" },
	{ numeric: "591", iso2: "PA", iso3: "PAN", name: "Panama" },
	{ numeric: "598", iso2: "PG", iso3: "PNG", name: "Papua New Guinea" },
	{ numeric: "600", iso2: "PY", iso3: "PRY", name: "Paraguay" },
	{ numeric: "604", iso2: "PE", iso3: "PER", name: "Peru" },
	{ numeric: "608", iso2: "PH", iso3: "PHL", name: "Philippines" },
	{ numeric: "612", iso2: "PN", iso3: "PCN", name: "Pitcairn" },
	{ numeric: "616", iso2: "PL", iso3: "POL", name: "Poland" },
	{ numeric: "620", iso2: "PT", iso3: "PRT", name: "Portugal" },
	{ numeric: "624", iso2: "GW", iso3: "GNB", name: "Guinea-Bissau" },
	{ numeric: "626", iso2: "TL", iso3: "TLS", name: "Timor-Leste" },
	{ numeric: "630", iso2: "PR", iso3: "PRI", name: "Puerto Rico" },
	{ numeric: "634", iso2: "QA", iso3: "QAT", name: "Qatar" },
	{ numeric: "638", iso2: "RE", iso3: "REU", name: "Réunion" },
	{ numeric: "642", iso2: "RO", iso3: "ROU", name: "Romania" },
	{ numeric: "643", iso2: "RU", iso3: "RUS", name: "Russia" },
	{ numeric: "646", iso2: "RW", iso3: "RWA", name: "Rwanda" },
	{ numeric: "652", iso2: "BL", iso3: "BLM", name: "Saint Barthélemy" },
	{ numeric: "654", iso2: "SH", iso3: "SHN", name: "Saint Helena" },
	{
		numeric: "659",
		iso2: "KN",
		iso3: "KNA",
		name: "Saint Kitts and Nevis",
	},
	{ numeric: "660", iso2: "AI", iso3: "AIA", name: "Anguilla" },
	{ numeric: "662", iso2: "LC", iso3: "LCA", name: "Saint Lucia" },
	{ numeric: "663", iso2: "MF", iso3: "MAF", name: "Saint Martin" },
	{
		numeric: "666",
		iso2: "PM",
		iso3: "SPM",
		name: "Saint Pierre and Miquelon",
	},
	{
		numeric: "670",
		iso2: "VC",
		iso3: "VCT",
		name: "Saint Vincent and the Grenadines",
	},
	{ numeric: "674", iso2: "SM", iso3: "SMR", name: "San Marino" },
	{
		numeric: "678",
		iso2: "ST",
		iso3: "STP",
		name: "Sao Tome and Principe",
	},
	{ numeric: "682", iso2: "SA", iso3: "SAU", name: "Saudi Arabia" },
	{ numeric: "686", iso2: "SN", iso3: "SEN", name: "Senegal" },
	{ numeric: "688", iso2: "RS", iso3: "SRB", name: "Serbia" },
	{ numeric: "690", iso2: "SC", iso3: "SYC", name: "Seychelles" },
	{ numeric: "694", iso2: "SL", iso3: "SLE", name: "Sierra Leone" },
	{ numeric: "702", iso2: "SG", iso3: "SGP", name: "Singapore" },
	{ numeric: "703", iso2: "SK", iso3: "SVK", name: "Slovakia" },
	{ numeric: "704", iso2: "VN", iso3: "VNM", name: "Vietnam" },
	{ numeric: "705", iso2: "SI", iso3: "SVN", name: "Slovenia" },
	{ numeric: "706", iso2: "SO", iso3: "SOM", name: "Somalia" },
	{ numeric: "710", iso2: "ZA", iso3: "ZAF", name: "South Africa" },
	{ numeric: "716", iso2: "ZW", iso3: "ZWE", name: "Zimbabwe" },
	{ numeric: "724", iso2: "ES", iso3: "ESP", name: "Spain" },
	{ numeric: "728", iso2: "SS", iso3: "SSD", name: "S. Sudan" },
	{ numeric: "729", iso2: "SD", iso3: "SDN", name: "Sudan" },
	{ numeric: "732", iso2: "EH", iso3: "ESH", name: "W. Sahara" },
	{ numeric: "740", iso2: "SR", iso3: "SUR", name: "Suriname" },
	{
		numeric: "744",
		iso2: "SJ",
		iso3: "SJM",
		name: "Svalbard and Jan Mayen",
	},
	{ numeric: "748", iso2: "SZ", iso3: "SWZ", name: "eSwatini" },
	{ numeric: "752", iso2: "SE", iso3: "SWE", name: "Sweden" },
	{ numeric: "756", iso2: "CH", iso3: "CHE", name: "Switzerland" },
	{ numeric: "760", iso2: "SY", iso3: "SYR", name: "Syria" },
	{ numeric: "762", iso2: "TJ", iso3: "TJK", name: "Tajikistan" },
	{ numeric: "764", iso2: "TH", iso3: "THA", name: "Thailand" },
	{ numeric: "768", iso2: "TG", iso3: "TGO", name: "Togo" },
	{ numeric: "772", iso2: "TK", iso3: "TKL", name: "Tokelau" },
	{ numeric: "776", iso2: "TO", iso3: "TON", name: "Tonga" },
	{
		numeric: "780",
		iso2: "TT",
		iso3: "TTO",
		name: "Trinidad and Tobago",
	},
	{ numeric: "784", iso2: "AE", iso3: "ARE", name: "United Arab Emirates" },
	{ numeric: "788", iso2: "TN", iso3: "TUN", name: "Tunisia" },
	{ numeric: "792", iso2: "TR", iso3: "TUR", name: "Turkey" },
	{ numeric: "795", iso2: "TM", iso3: "TKM", name: "Turkmenistan" },
	{
		numeric: "796",
		iso2: "TC",
		iso3: "TCA",
		name: "Turks and Caicos Islands",
	},
	{ numeric: "798", iso2: "TV", iso3: "TUV", name: "Tuvalu" },
	{ numeric: "800", iso2: "UG", iso3: "UGA", name: "Uganda" },
	{ numeric: "804", iso2: "UA", iso3: "UKR", name: "Ukraine" },
	{ numeric: "807", iso2: "MK", iso3: "MKD", name: "Macedonia" },
	{ numeric: "818", iso2: "EG", iso3: "EGY", name: "Egypt" },
	{ numeric: "826", iso2: "GB", iso3: "GBR", name: "United Kingdom" },
	{ numeric: "831", iso2: "GG", iso3: "GGY", name: "Guernsey" },
	{ numeric: "832", iso2: "JE", iso3: "JEY", name: "Jersey" },
	{ numeric: "833", iso2: "IM", iso3: "IMN", name: "Isle of Man" },
	{ numeric: "834", iso2: "TZ", iso3: "TZA", name: "Tanzania" },
	{
		numeric: "840",
		iso2: "US",
		iso3: "USA",
		name: "United States of America",
	},
	{
		numeric: "850",
		iso2: "VI",
		iso3: "VIR",
		name: "United States Virgin Islands",
	},
	{ numeric: "854", iso2: "BF", iso3: "BFA", name: "Burkina Faso" },
	{ numeric: "858", iso2: "UY", iso3: "URY", name: "Uruguay" },
	{ numeric: "860", iso2: "UZ", iso3: "UZB", name: "Uzbekistan" },
	{ numeric: "862", iso2: "VE", iso3: "VEN", name: "Venezuela" },
	{ numeric: "876", iso2: "WF", iso3: "WLF", name: "Wallis and Futuna" },
	{ numeric: "882", iso2: "WS", iso3: "WSM", name: "Samoa" },
	{ numeric: "887", iso2: "YE", iso3: "YEM", name: "Yemen" },
	{ numeric: "894", iso2: "ZM", iso3: "ZMB", name: "Zambia" },

	// Non-ISO / disputed entries that the world-atlas geometry ships with no
	// numeric id. Synthetic numerics keep the table keyable; these join the
	// geometry by NAME (their `properties.name`), not numeric.
	{ numeric: "383", iso2: "XK", iso3: "XKX", name: "Kosovo" },
	{ numeric: "900", iso2: "", iso3: "", name: "N. Cyprus" },
	{ numeric: "901", iso2: "", iso3: "", name: "Somaliland" },
]

export const countryLookup = {
	byNumeric: new Map(ISO_COUNTRIES.map((row) => [row.numeric, row])),
	byIso2: new Map(
		ISO_COUNTRIES.filter((row) => row.iso2 !== "").map((row) => [
			row.iso2,
			row,
		]),
	),
	byIso3: new Map(
		ISO_COUNTRIES.filter((row) => row.iso3 !== "").map((row) => [
			row.iso3,
			row,
		]),
	),
	byName: new Map(ISO_COUNTRIES.map((row) => [row.name.toLowerCase(), row])),
}
